project.exe: project.c optimum_load.c energy_output.c energy_copper.c energy_iron.c cost.c
	gcc project.c optimum_load.c energy_output.c energy_copper.c energy_iron.c cost.c -o project.exe
run: project.exe
	project.exe